{
  "expire": null,
  "issue": {
    "source": "気象庁",
    "time": "2019/10/12 10:49:00",
    "type": "ScaleAndDestination",
    "correct": "None"
  },
  "earthquake": {
    "time": "2019/10/12 10:46:00",
    "hypocenter": {
      "name": "茨城県沖",
      "latitude": 36.3,
      "longitude": 140.9,
      "depth": 30,
      "magnitude": 2.9
    },
    "maxScale": 10,
    "domesticTsunami": "None",
    "foreignTsunami": "Unknown"
  },
  "points": []
}